### ISSUE TITLE
Certain non-solid blocks place weirdly

### ISSUE THREAD

**Issue by BakinDP** [HiWord9/BuildingShift#2]
Blocks like torches, levers, buttons etc are placed on bottom block, when trying to place it on side block, with shift enabled

**Comment by BakinDP** [comment]
![image](https://github.com/HiWord9/BuildingShift/assets/74774853/22b7eaec-5a7b-4338-a57e-aa14fc1cf37a)

**Comment by BakinDP** [comment]
![image](https://github.com/HiWord9/BuildingShift/assets/74774853/96af98c7-0c51-46c3-b24c-6993abd667ab)

**Comment by HiWord9** [comment]
i found out that side the torch is placed on depends on player's rotation, and it seems to be calculated on server or in way i did not found

**Comment by HiWord9** [comment]
fixed in singleplayer in 1.1.0

**Comment by BakinDP** [comment]
Tested in singleplayer, but since it's technically a local server, maybe there is no difference. 

Will extensively test both old and new versions to fulfill the report!

**Comment by BakinDP** [comment]
Discovered by now, placing behavior:

- does depend on rotation
- changed with players' relative position to targeted block

But of 1.1.0 this appears to be fixed in atleast singleplayer, since as I have found out that some non-vanilla servers have protection against mods, such as Building Shift (servers would refuse player to build anything completely, while shift is active), so it may not be a problem in most cases.

https://www.youtube.com/watch?v=-WHLx113v5U

Thanks for making this amazing mod better!

**Comment by HiWord9** [comment]
So, it's been a long time with this bug, and i would like to anounce something:
The bug is executed on server due to how client-side makes block being placed instead of communication with interactable block, so i (more likely) can not fix it only on client-side.
Since 1.2.0, the mod can be installed on server and it fixes the bug, so im closing the issue as it potentionally fixed. More info about server-side instance of mod can be found on mod's modrinth main page.
